# 手动发布包到 NPM

name: 📦 Manual Publish to NPM

on:
  workflow_dispatch:
    inputs:
      parameters:
        description: '🤔 没想好参数'
        required: false

permissions:
  contents: write
  pull-requests: read

# 不允许同时进行多个部署，跳过非正在运行、非最新队列的运行队列，且不取消正在运行的工作流
concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  # 构建
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # [Publishing packages with provenance via GitHub Actions](https://docs.npmjs.com/generating-provenance-statements)
      contents: write # 创建 Release 要用这个权限
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: 📦 Setup pnpm # 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 📦 Install dependencies # 安装依赖
        run: pnpm install
      - name: 🚀 Build & Publish Package # 编译并发布
        run: npm publish --provenance
        if: | # 仅在 Moushudyx/foreslash 下发布, 防止别人 fork 后误操作
          startsWith(github.repository, 'Moushudyx')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🔎 Detect version # 获取 version
        id: version_check
        run: |
          # 获取当前版本
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: 📝 Generate release notes # 生成 Release 相关信息
        id: changelog
        run: |
          # 提取 CHANGELOG.md 中第一个二级标题下的内容
          awk '
          /^## / && !found {
            found=1;
            next
          }
          found && /^#/ {
            exit
          }
          found' CHANGELOG.md > release_notes.txt

          # 生成日期格式 YYYY-MM-DD
          DATE=$(date +'%Y-%m-%d')

          # 输出
          echo "release_title=Version ${{ steps.version_check.outputs.version }} - $DATE" >> $GITHUB_OUTPUT
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat release_notes.txt)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          # echo "release_notes=$(cat release_notes.txt)" >> $GITHUB_OUTPUT
          echo "Version ${{ steps.version_check.outputs.version }} - $DATE"
          echo "$(cat release_notes.txt)"
      - name: 🚀 Create GitHub Release # 发布 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version_check.outputs.version }}
          name: ${{ steps.changelog.outputs.release_title }}
          body: ${{ steps.changelog.outputs.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
